# -*- coding: utf-8 -*-
"""01_data_acquisition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qKM8dZP29cZFyEi4SQEp3ogYIXV9xvh
"""

"""
data_acquisition.py
--------------------

Coleta padronizada de dados da NBA.
Todas as funções retornam TEAM_ID + TEAM_NAME + métricas específicas.
Formato dos nomes segue exatamente o padrão da NBA API.
"""

import pandas as pd
from nba_api.stats.static import teams
from nba_api.stats.endpoints import (
    leaguedashteamstats,
    leaguedashteamshotlocations,
    leaguedashplayerstats
)

# ============================================================
# Helpers: Lookup TEAM_ID <-> TEAM_NAME
# ============================================================

teams_lookup = pd.DataFrame(teams.get_teams())
teams_lookup = teams_lookup.rename(columns={
    "id": "TEAM_ID",
    "full_name": "TEAM_NAME",
    "abbreviation": "TEAM_ABBREVIATION"
})[["TEAM_ID", "TEAM_NAME", "TEAM_ABBREVIATION"]]


# ============================================================
# 1. Offensive Stats (Advanced + Four Factors)
# ============================================================

def get_offensive_stats(season: str, season_type: str) -> pd.DataFrame:

    adv = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Advanced",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    ff = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Four Factors",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    cols_adv = [
        "TEAM_ID", "OFF_RATING", "NET_RATING", "AST_PCT",
        "AST_TO", "AST_RATIO", "TM_TOV_PCT", "EFG_PCT",
        "TS_PCT", "PACE", "E_PACE"
    ]

    cols_ff = ["TEAM_ID", "FTA_RATE", "OREB_PCT"]

    df = adv[cols_adv].merge(ff[cols_ff], on="TEAM_ID")
    df = df.merge(teams_lookup[["TEAM_ID", "TEAM_NAME"]], on="TEAM_ID")

    return df


# ============================================================
# 2. Defensive Stats (Defense + Opponent)
# ============================================================

def get_defensive_stats(season: str, season_type: str) -> pd.DataFrame:

    defense = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Defense",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    opponent = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Opponent",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    cols_def = [
        "TEAM_ID", "DEF_RATING", "STL", "BLK",
        "DREB_PCT", "OPP_PTS_2ND_CHANCE", "OPP_PTS_PAINT"
    ]

    cols_op = [
        "TEAM_ID", "OPP_FGM", "OPP_FGA", "OPP_FG_PCT",
        "OPP_FG3M", "OPP_FG3A", "OPP_FG3_PCT", "OPP_FTA",
        "OPP_REB", "OPP_AST", "OPP_TOV", "OPP_PTS"
    ]

    df = defense[cols_def].merge(opponent[cols_op], on="TEAM_ID")
    df = df.merge(teams_lookup[["TEAM_ID", "TEAM_NAME"]], on="TEAM_ID")

    return df


# ============================================================
# 3. Bench Points %
# ============================================================

def get_bench_points(season: str, season_type: str) -> pd.DataFrame:

    bench = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Base",
        starter_bench_nullable="Bench",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    total = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Base",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    bench = bench[["TEAM_ID", "PTS"]].rename(columns={"PTS": "BENCH_PTS"})
    total = total[["TEAM_ID", "PTS"]].rename(columns={"PTS": "TOTAL_PTS"})

    df = bench.merge(total, on="TEAM_ID")
    df["BENCH_PTS_PCT"] = df["BENCH_PTS"] / df["TOTAL_PTS"]

    df = df.merge(teams_lookup[["TEAM_ID", "TEAM_NAME"]], on="TEAM_ID")

    return df


# ============================================================
# 4. Shot Profile (zonas + scoring)
# ============================================================

def get_shot_locations(season: str, season_type: str) -> pd.DataFrame:

    scoring = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense="Scoring",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    shot = leaguedashteamshotlocations.LeagueDashTeamShotLocations(
        season=season,
        measure_type_simple="Base",
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    # calcular FG3_PCT
    fgm3 = (
        shot["Left Corner 3", "FGM"] +
        shot["Right Corner 3", "FGM"] +
        shot["Above the Break 3", "FGM"]
    )
    fga3 = (
        shot["Left Corner 3", "FGA"] +
        shot["Right Corner 3", "FGA"] +
        shot["Above the Break 3", "FGA"]
    )
    fg3_pct = fgm3 / fga3

    df = pd.DataFrame()
    df["TEAM_NAME"] = shot[("", "TEAM_NAME")]

    df["RIM_FG_PCT"] = shot["Restricted Area", "FG_PCT"]
    df["RIM_FGA"] = shot["Restricted Area", "FGA"]

    df["PAINT_FG_PCT"] = shot["In The Paint (Non-RA)", "FG_PCT"]
    df["PAINT_FGA"] = shot["In The Paint (Non-RA)", "FGA"]

    df["MID_RANGE_FG_PCT"] = shot["Mid-Range", "FG_PCT"]
    df["MID_RANGE_FGA"] = shot["Mid-Range", "FGA"]

    df["FG3_PCT"] = fg3_pct
    df["FG3_FGA"] = fga3

    df["PCT_PTS_2PT"] = scoring["PCT_PTS_2PT"]
    df["PCT_PTS_3PT"] = scoring["PCT_PTS_3PT"]

    df = df.merge(teams_lookup[["TEAM_ID", "TEAM_NAME"]], on="TEAM_NAME")

    return df


# ============================================================
# 5. USG% Líderes
# ============================================================

def get_usage_stars(season: str, season_type: str, min_games: int = 30):

    players = leaguedashplayerstats.LeagueDashPlayerStats(
        season=season,
        season_type_all_star=season_type,
        measure_type_detailed_defense="Advanced",
        per_mode_detailed="PerGame"
    ).get_data_frames()[0]

    players = players[["PLAYER_NAME", "TEAM_ID", "GP", "USG_PCT"]]
    players = players[players["GP"] >= min_games]

    result = []

    for tid in teams_lookup["TEAM_ID"]:
        team_df = players[players["TEAM_ID"] == tid].sort_values("USG_PCT", ascending=False).head(2)
        if len(team_df) < 2:
            continue

        result.append({
            "TEAM_ID": tid,
            "TEAM_NAME": teams_lookup.loc[teams_lookup["TEAM_ID"] == tid, "TEAM_NAME"].values[0],
            "LEADER_1": team_df.iloc[0]["PLAYER_NAME"],
            "USG_L1": round(team_df.iloc[0]["USG_PCT"], 1),
            "LEADER_2": team_df.iloc[1]["PLAYER_NAME"],
            "USG_L2": round(team_df.iloc[1]["USG_PCT"], 1)
        })

    return pd.DataFrame(result)