# -*- coding: utf-8 -*-
"""data_acquisition.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEYhyuconoNAkUICqQDtQUl9t8N3HDVy
"""

"""
data_acquisition.py
--------------------

Módulo responsável pela coleta de dados da NBA usando a biblioteca nba_api.
Contém funções reutilizáveis para extrair estatísticas ofensivas, defensivas,
perfil de arremessos, USG% e dados auxiliares como TEAM_ID e abreviações.

Este arquivo deve ser importado pelos notebooks do projeto e nunca editado
dentro de ambientes interativos. Assim o pipeline de dados permanece limpo,
modular e fácil de dar manutenção.
"""

import pandas as pd
from nba_api.stats.static import teams
from nba_api.stats.endpoints import (
    leaguedashteamstats,
    leaguedashteamshotlocations,
    leaguedashplayerstats
)

# ============================================================
#   Helpers: buscar TEAM_ID e TEAM_ABBREVIATION
# ============================================================

def find_ID_by_name(team_name: str) -> int:
    """Retorna o TEAM_ID dado o nome completo do time."""
    info = teams.find_teams_by_full_name(team_name)
    return info[0]["id"]


def find_abb_by_name(team_name: str) -> str:
    """Retorna a abreviação (ex: 'GSW') dado o nome completo."""
    info = teams.find_teams_by_full_name(team_name)
    return info[0]["abbreviation"]


def getting_ID_row_by_name(team_list, df_teams):
    """
    Adiciona TEAM_ID ao DataFrame que contém uma coluna 'TEAMS'
    com os nomes completos das equipes.
    """
    mapping = {team: find_ID_by_name(team) for team in team_list}

    for team in df_teams["TEAMS"]:
        if team in mapping:
            df_teams.loc[df_teams["TEAMS"] == team, "TEAM_ID"] = mapping[team]

    return df_teams

# ============================================================
#   Offensive Stats
# ============================================================

def get_ofensive_stats(season: str, season_type: str) -> pd.DataFrame:
    """
    Retorna estatísticas avançadas ofensivas da NBA para a temporada especificada.
    """
    advanced = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Advanced',
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    cols_adv = [
        'TEAM_ID', 'OFF_RATING', 'NET_RATING', 'AST_PCT',
        'AST_TO', 'AST_RATIO', 'TM_TOV_PCT', 'EFG_PCT',
        'TS_PCT', 'PACE', 'E_PACE'
    ]

    four_factors = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Four Factors',
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    cols_ff = ['TEAM_ID', 'FTA_RATE', 'OREB_PCT']

    df = pd.merge(advanced[cols_adv], four_factors[cols_ff], on="TEAM_ID")
    return df

# ============================================================
#   Defensive Stats
# ============================================================

def get_defensive_stats(season: str, season_type: str) -> pd.DataFrame:
    """
    Retorna estatísticas defensivas combinando Defense + Opponent.
    """
    defense = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Defense',
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    cols_def = [
        'TEAM_NAME', 'DEF_RATING', 'STL', 'BLK',
        'DREB_PCT', 'OPP_PTS_2ND_CHANCE', 'OPP_PTS_PAINT'
    ]

    opponent = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Opponent',
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    cols_op = [
        'TEAM_NAME', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
        'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTA',
        'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_PTS'
    ]

    df = pd.merge(defense[cols_def], opponent[cols_op], on='TEAM_NAME')

    return df

# ============================================================
#   Bench Points %
# ============================================================

def get_bench_points(season: str, season_type: str) -> pd.DataFrame:
    """
    Retorna a porcentagem de pontos do banco (BENCH_PTS / TEAM_PTS).
    """
    bench = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Base',
        starter_bench_nullable='Bench',
        season_type_all_star=season_type
    ).get_data_frames()[0]

    team = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Base',
        season_type_all_star=season_type
    ).get_data_frames()[0]

    bench = bench[['TEAM_ID', 'PTS']].rename(columns={'PTS': 'BENCH_PTS'})
    team = team[['TEAM_ID', 'PTS']]

    df = pd.merge(bench, team, on='TEAM_ID')
    df['BENCH_PTS_PCT'] = df['BENCH_PTS'] / df['PTS']

    return df

# ============================================================
#   Shot Profile (Identidade)
# ============================================================

def get_shot_locations(season: str, season_type: str) -> pd.DataFrame:
    """
    Retorna perfil de arremessos (FGA%, FG% por zona, 3PT%) e estatísticas
    complementares de 'Scoring'.
    """
    scoring = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        measure_type_detailed_defense='Scoring',
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    shot = leaguedashteamshotlocations.LeagueDashTeamShotLocations(
        season=season,
        measure_type_simple='Base',
        per_mode_detailed="PerGame",
        season_type_all_star=season_type
    ).get_data_frames()[0]

    # FG% de 3
    fgm_3 = (
        shot['Left Corner 3', 'FGM'] +
        shot['Right Corner 3', 'FGM'] +
        shot['Above the Break 3', 'FGM']
    )

    fga_3 = (
        shot['Left Corner 3', 'FGA'] +
        shot['Right Corner 3', 'FGA'] +
        shot['Above the Break 3', 'FGA']
    )

    fgpct_3 = fgm_3 / fga_3

    df = pd.DataFrame()
    df["TEAM_NAME"] = shot[("", "TEAM_NAME")]
    df["RIM_PCT"] = shot["Restricted Area", "FG_PCT"]
    df["RIM_FGA"] = shot["Restricted Area", "FGA"]
    df["PAINT_PCT"] = shot["In The Paint (Non-RA)", "FG_PCT"]
    df["PAINT_FGA"] = shot["In The Paint (Non-RA)", "FGA"]
    df["MID_PCT"] = shot["Mid-Range", "FG_PCT"]
    df["MID_FGA"] = shot["Mid-Range", "FGA"]
    df["FG3_PCT"] = fgpct_3
    df["FG3_FGA"] = fga_3
    df["PCT_PTS_2PT"] = scoring["PCT_PTS_2PT"]
    df["PCT_PTS_3PT"] = scoring["PCT_PTS_3PT"]

    return df

# ============================================================
#   USG% Líderes
# ============================================================

def get_usage_stars(season: str, season_type: str, min_games: int = 30) -> pd.DataFrame:
    """
    Retorna os 2 jogadores com maior USG% de cada time.
    """
    df_teams = pd.DataFrame()
    df_teams["TEAMS"] = [team["full_name"] for team in teams.get_teams()]
    df_teams = getting_ID_row_by_name(df_teams["TEAMS"], df_teams)

    df = leaguedashplayerstats.LeagueDashPlayerStats(
        season=season,
        season_type_all_star=season_type,
        per_mode_detailed='PerGame',
        measure_type_detailed_defense='Advanced'
    ).get_data_frames()[0]

    df = df[["PLAYER_NAME", "TEAM_ID", "TEAM_ABBREVIATION", "GP", "USG_PCT"]]
    df = df[df['GP'] >= min_games]

    result = {
        "TEAM_ID": [],
        "LEADER_1": [], "USG_L1": [],
        "LEADER_2": [], "USG_L2": []
    }

    for tid in df_teams["TEAM_ID"].astype(int):
        team_df = df[df['TEAM_ID'] == tid]
        top2 = team_df.sort_values(by="USG_PCT", ascending=False).head(2)

        if len(top2) < 2:
            continue

        result["TEAM_ID"].append(tid)
        result["LEADER_1"].append(top2.iloc[0]["PLAYER_NAME"])
        result["USG_L1"].append(round(top2.iloc[0]["USG_PCT"], 1))
        result["LEADER_2"].append(top2.iloc[1]["PLAYER_NAME"])
        result["USG_L2"].append(round(top2.iloc[1]["USG_PCT"], 1))

    return pd.DataFrame(result)